name: taskline_app
description: "TASKLINE APP - Secure Train Travel & Priority Task Companion with Android SMS and Call Log auto-processing."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  # For local secure AES/DES and hashing representation
  crypto: ^3.0.3 
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
